name: Check
on: [push]
jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: npm
      - name: Dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
